# Generated by Django 5.2.10 on 2026-07-15 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def close_duplicate_open_sessions(apps, schema_editor):
    AttendanceSession = apps.get_model("attendance", "AttendanceSession")
    qs = (AttendanceSession.objects.filter(is_open=True)
          .values("employee_id").annotate(c=Count("id")).filter(c__gt=1))
    for row in qs:
        sessions = list(AttendanceSession.objects.filter(employee_id=row["employee_id"], is_open=True).order_by("-clock_in_time", "-id"))
        for old in sessions[1:]:
            # Do not infer or rewrite a historical clock-out time. Mark older duplicate as closed/flagged only.
            old.is_open = False
            old.save(update_fields=["is_open"])

def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0003_alter_attendanceevent_id_alter_attendancesession_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DivisionRosterEditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_rostered", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                (
                    "leave_type",
                    models.CharField(
                        choices=[
                            ("ANNUAL", "Annual"),
                            ("SICK", "Sick"),
                            ("UNPAID", "Unpaid"),
                            ("TRAINING", "Training"),
                            ("OTHER", "Other"),
                        ],
                        default="ANNUAL",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="PinAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.GenericIPAddressField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[("SUBJECT", "Subject"), ("WITNESS", "Witness")],
                        max_length=16,
                    ),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "first_failed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(close_duplicate_open_sessions, noop_reverse),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open", True)),
                fields=("employee",),
                name="uniq_open_session_per_employee",
            ),
        ),
        migrations.AddField(
            model_name="divisionrostereditor",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="attendance.division"
            ),
        ),
        migrations.AddField(
            model_name="divisionrostereditor",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.division",
            ),
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="employee",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to="attendance.employee",
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_requests",
                to="attendance.employee",
            ),
        ),
        migrations.AddField(
            model_name="pinattempt",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pin_attempts",
                to="attendance.employee",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_assignments",
                to="attendance.division",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_assignments",
                to="attendance.employee",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="entered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts_entered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_templates",
                to="attendance.division",
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.shifttemplate",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="divisionrostereditor",
            unique_together={("user", "division")},
        ),
        migrations.AddIndex(
            model_name="pinattempt",
            index=models.Index(
                fields=["employee", "client_ip", "purpose"],
                name="attendance__employe_f7bc8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pinattempt",
            index=models.Index(
                fields=["last_failed_at"], name="attendance__last_fa_e1f392_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pinattempt",
            unique_together={("employee", "client_ip", "purpose")},
        ),
        migrations.AlterUniqueTogether(
            name="shifttemplate",
            unique_together={("division", "name")},
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["date", "division", "status"],
                name="attendance__date_0bb690_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shiftassignment",
            index=models.Index(
                fields=["employee", "date"], name="attendance__employe_5bc4a9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftassignment",
            unique_together={("employee", "date", "start_time", "end_time")},
        ),
    ]
