# Generated by Django 5.2.10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_attendanceevent_id_alter_attendancesession_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Division",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_rostered", models.BooleanField(default=True)),
                ("division", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="attendance.division")),
                ("employee", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="profile", to="attendance.employee")),
            ],
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("leave_type", models.CharField(choices=[("ANNUAL", "Annual"), ("SICK", "Sick"), ("UNPAID", "Unpaid"), ("TRAINING", "Training"), ("OTHER", "Other")], default="ANNUAL", max_length=20)),
                ("status", models.CharField(choices=[("SUBMITTED", "Submitted"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="SUBMITTED", max_length=20)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="leave_requests", to="attendance.employee")),
            ],
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=60)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("division", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shift_templates", to="attendance.division")),
            ],
            options={"unique_together": {("division", "name")}},
        ),
        migrations.CreateModel(
            name="DivisionRosterEditor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("division", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="attendance.division")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={"unique_together": {("user", "division")}},
        ),
        migrations.CreateModel(
            name="ShiftAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("SUBMITTED", "Submitted"), ("APPROVED", "Approved")], default="DRAFT", max_length=12)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("approved_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="shifts_approved", to=settings.AUTH_USER_MODEL)),
                ("division", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shift_assignments", to="attendance.division")),
                ("employee", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="shift_assignments", to="attendance.employee")),
                ("entered_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="shifts_entered", to=settings.AUTH_USER_MODEL)),
                ("template", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="attendance.shifttemplate")),
            ],
            options={
                "indexes": [
                    models.Index(fields=["date", "division", "status"], name="attendance__date_0bb690_idx"),
                    models.Index(fields=["employee", "date"], name="attendance__employe_5bc4a9_idx"),
                ],
                "unique_together": {("employee", "date", "start_time", "end_time")},
            },
        ),
    ]
