# Generated by Django 5.2.10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Count


def close_duplicate_open_sessions(apps, schema_editor):
    AttendanceSession = apps.get_model("attendance", "AttendanceSession")
    duplicates = (
        AttendanceSession.objects.filter(is_open=True)
        .values("employee_id")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    for row in duplicates:
        sessions = list(
            AttendanceSession.objects.filter(
                employee_id=row["employee_id"],
                is_open=True,
            ).order_by("-clock_in_time", "-id")
        )
        for older_session in sessions[1:]:
            older_session.is_open = False
            older_session.save(update_fields=["is_open"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance",
            "0004_division_employeeprofile_leaverequest_shifttemplate_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PinAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_ip", models.GenericIPAddressField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[("SUBJECT", "Subject"), ("WITNESS", "Witness")],
                        max_length=16,
                    ),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "first_failed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("locked_until", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pin_attempts",
                        to="attendance.employee",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "client_ip", "purpose"],
                        name="attendance__employe_f7bc8d_idx",
                    ),
                    models.Index(
                        fields=["last_failed_at"],
                        name="attendance__last_fa_e1f392_idx",
                    ),
                ],
                "unique_together": {("employee", "client_ip", "purpose")},
            },
        ),
        migrations.RunPython(close_duplicate_open_sessions, noop_reverse),
        migrations.AddConstraint(
            model_name="attendancesession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_open", True)),
                fields=("employee",),
                name="uniq_open_session_per_employee",
            ),
        ),
    ]
