# Generated by Django 5.2.10 on 2026-07-15 15:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_security_hardening"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("FORGOT_CLOCK_IN", "Forgot clock in"),
                            ("FORGOT_CLOCK_OUT", "Forgot clock out"),
                            ("WRONG_TIME", "Wrong time"),
                            ("WRONG_ACTION", "Wrong action"),
                            ("OTHER", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("requested_clock_in", models.DateTimeField(blank=True, null=True)),
                ("requested_clock_out", models.DateTimeField(blank=True, null=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("manager_note", models.TextField(blank=True, default="")),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="correction_requests",
                        to="attendance.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="correction_requests",
                        to="attendance.attendancesession",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["employee", "status", "created_at"],
                        name="attendance__employe_def6fe_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="attendance__status_70e50f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "SUBMITTED")),
                        fields=("employee", "session", "request_type"),
                        name="uniq_submitted_correction_per_session_type",
                    )
                ],
            },
        ),
    ]
