# Generated by Django 5.2.10 on 2026-07-15 23:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_employee_self_service"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("NEW_LEAVE_REQUEST", "New leave request"),
                            ("NEW_CORRECTION_REQUEST", "New correction request"),
                            ("NO_SHOW", "No show"),
                            ("MISSING_CLOCKOUT", "Missing clock-out"),
                            ("PROXY_ATTENDANCE", "Proxy attendance"),
                            ("PIN_LOCKOUT", "PIN lockout"),
                            ("DAILY_SUMMARY", "Daily summary"),
                        ],
                        max_length=40,
                    ),
                ),
                ("dedupe_key", models.CharField(max_length=220, unique=True)),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("is_workday", models.BooleanField(default=False)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, default="", max_length=160)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="division",
            name="schedule_mode",
            field=models.CharField(
                choices=[("ROSTER", "Roster-based"), ("FIXED", "Fixed hours")],
                default="ROSTER",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="source",
            field=models.CharField(
                choices=[("MANUAL", "Manual roster"), ("FIXED", "Fixed schedule")],
                default="MANUAL",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="FixedScheduleRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("is_workday", models.BooleanField(default=False)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fixed_schedule_rules",
                        to="attendance.division",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shiftassignment",
            name="fixed_schedule_rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_shifts",
                to="attendance.fixedschedulerule",
            ),
        ),
        migrations.AddConstraint(
            model_name="shiftassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source", "FIXED")),
                fields=("employee", "date"),
                name="uniq_fixed_shift_employee_date",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="division",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_deliveries",
                to="attendance.division",
            ),
        ),
        migrations.AddField(
            model_name="notificationdelivery",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notification_deliveries",
                to="attendance.employee",
            ),
        ),
        migrations.AddField(
            model_name="scheduleexception",
            name="division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_exceptions",
                to="attendance.division",
            ),
        ),
        migrations.AddIndex(
            model_name="fixedschedulerule",
            index=models.Index(
                fields=["division", "weekday"], name="idx_fixed_rule_div_weekday"
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedschedulerule",
            constraint=models.UniqueConstraint(
                fields=("division", "weekday"), name="uniq_fixed_rule_division_weekday"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(
                fields=["status", "event_type", "target_date"],
                name="idx_notif_status_event_date",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationdelivery",
            index=models.Index(fields=["created_at"], name="idx_notif_created"),
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["division", "date"], name="idx_sched_exc_div_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleexception",
            constraint=models.UniqueConstraint(
                fields=("division", "date"),
                name="uniq_schedule_exception_division_date",
            ),
        ),
    ]
